routes/admin.php
<?php

Route::get('/dashboard', 'DashboardController@index')->name('admin.index');



Route::resource('subjects', 'SubjectController');

Route::get('files/create', 'FileUploadController@create')->name('files.create');
Route::post('files', 'FileUploadController@store')->name('files.store');
Route::get('files/{subject}/{file}', 'FileUploadController@show')->name('files.show');
Route::get('files', 'FileUploadController@index')->name('files.index');
Route::patch('files/{file}', 'FileUploadController@update')->name('files.update');
Route::delete('files/{file}', 'FileUploadController@destroy')->name('files.destroy');
//Route::resource('fileable.files', 'FileUploadController')->except(['fileable.file.index', 'fileable.file.create', 'fileable.file.store']);

Route::get('downloadables/create', 'DownloadableController@create')->name('downloadables.create');
Route::post('downloadables', 'DownloadableController@store')->name('downloadables.store');
Route::get('downloadables/{category}/{downloadable}', 'DownloadableController@show')->name('downloadables.show');
Route::get('downloadables', 'DownloadableController@index')->name('downloadables.index');
Route::patch('downloadables/{downloadable}', 'DownloadableController@update')->name('downloadables.update');
Route::delete('downloadables/{downloadable}', 'DownloadableController@destroy')->name('downloadables.destroy');
//Route::resource('downloadables', 'DownloadableController');

Route::post('jobs', 'JobController@store')->name('jobs.store');
Route::get('jobs', 'JobController@index')->name('jobs.index');
Route::get('jobs/{subCategory}/{job}', 'JobController@show')->name('jobs.show');
Route::patch('jobs/{job}', 'JobController@update')->name('jobs.update');
Route::delete('jobs/{job}', 'JobController@destroy')->name('jobs.destroy');
Route::get('jobs/create','JobController@create')->name('jobs.create');
//Route::resource('jobs', 'JobController');

//Route::resource('tests', 'TestController');
//Route::resource('jobs-tests', 'JobController');

Route::resource('tags', 'TagController');

Route::resource('blogs', 'BlogController');

Route::resource('useruploads', 'UserUploadController');

Route::get('useruploads/{userupload}', 'DownloadController@download')->name('downloads.download');

Route::get('user', 'DownloadController@sample')->name('downloads.sample');

Route::get('user-downloadables', 'DownloadableController@index')->name('user-downloadables.index');


Route::get('subject-quizzes/create', 'SubjectQuizController@create')->name('subject-quizzes.create');
Route::post('subject-quizzes', 'SubjectQuizController@store')->name('subject-quizzes.store');
Route::get('subject-quizzes/{subject}/{subject_quiz}', 'SubjectQuizController@show')->name('subject-quizzes.show');
Route::get('subject-quizzes', 'SubjectQuizController@index')->name('subject-quizzes.index');
Route::patch('subject-quizzes/{subject_quiz}', 'SubjectQuizController@update')->name('subject-quizzes.update');
Route::delete('subject-quizzes/{subject_quiz}', 'SubjectQuizController@destroy')->name('subject-quizzes.destroy');
//Route::resource('subject-quizzes', 'SubjectQuizController');

Route::get('job-quizzes/create', 'JobQuizController@create')->name('job-quizzes.create');
Route::post('job-quizzes', 'JobQuizController@store')->name('job-quizzes.store');
Route::get('job-quizzes/{job}/{job_quiz}', 'JobQuizController@show')->name('job-quizzes.show');
Route::get('job-quizzes', 'JobQuizController@index')->name('job-quizzes.index');
Route::patch('job-quizzes/{job_quiz}', 'JobQuizController@update')->name('job-quizzes.update');
Route::delete('job-quizzes/{job_quiz}', 'JobQuizController@destroy')->name('job-quizzes.destroy');
//Route::resource('job-quizzes', 'JobQuizController');

Route::get('test-quizzes/create', 'TestQuizController@create')->name('test-quizzes.create');
Route::post('test-quizzes', 'TestQuizController@store')->name('test-quizzes.store');
Route::get('test-quizzes/{category}/{test_quiz}', 'TestQuizController@show')->name('test-quizzes.show');
Route::get('test-quizzes', 'TestQuizController@index')->name('test-quizzes.index');
Route::patch('test-quizzes/{test_quiz}', 'TestQuizController@update')->name('test-quizzes.update');
Route::delete('test-quizzes/{test_quiz}', 'TestQuizController@destroy')->name('test-quizzes.destroy');
//Route::resource('test-quizzes', 'TestQuizController');

//Route::resource('course-quizzes', 'CourseQuizController');

//Route::post('course/{quiz}/{file_id}', 'CourseQuizController@deleteFile')->name('course.destroyFile');
Route::get('job-quizz/{job_quiz}/{file_id}', 'JobQuizController@deleteFile')->name('job-quiz.destroyFile');
Route::get('test-quizz/{test_quiz}/{file_id}', 'TestQuizController@deleteFile')->name('test-quiz.destroyFile');
Route::get('quiz/{quiz}/{file_id}', 'SubjectQuizController@deleteFile')->name('quiz.destroyFile');


Route::get('slider', 'SliderController@index')->name('slider');
//
Route::post('slider/{slider}/update', 'SliderController@update')->name('slider.update');

Route::get('about', 'AboutController@index')->name('admin.about');
//
Route::post('about/{about}/update', 'AboutController@update')->name('about.update');

Route::get('contact', 'ContactController@index')->name('admin.contact');
//
Route::post('contact/{contact}/update', 'ContactController@update')->name('contact.update');

Route::get('banner', 'BannerController@index')->name('banner');
//
Route::post('banner/{banner}/update', 'BannerController@update')->name('banner.update');

//Route::resource('slider', 'SliderController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('layouts.client');
//});

//Auth::routes();
Route::post('login/user', 'Auth\LoginController@login')->name('login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
Route::get('password/confirm', 'Auth\ConfirmPasswordController@showConfirmForm')->name('password.confirm');
Route::post('password/confirm', 'Auth\ConfirmPasswordController@confirm');

Route::get('/', 'ClientControllers\HomeController@index')->name('home');
//Route::get('/', function (){
//    return view('home',[
//        'subjects' => \App\Subject::all(),
//    ]);
//});
//Route::get('/about', 'ClientControllers\AboutController@index')->name('about');
//Route::get('/contact', 'ClientControllers\ContactController@index')->name('contact');
//Route::get('/jobs', 'ClientControllers\JobController@index')->name('jobs');
//Route::get('/tests', 'ClientControllers\AdmissionTestController@index')->name('tests');
//Route::get('/blogs', 'ClientControllers\BlogController@index')->name('blogs');
//Route::get('/blogs/detail', 'ClientControllers\BlogController@show')->name('blogs/detail');

app/Blog.php
<?php

namespace App;

use App\Helpers\GeneralTrait;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Intervention\Image\Facades\Image;

class Blog extends Model
{
    use GeneralTrait;
    protected $fillable = [
        'title',
        'slug',
        'excerpt',
        'body',
        'type',
        'image',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

    /**
     * @return MorphMany
     */
    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable')->whereNull('parent_id');
    }

    /**
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function getImageAttribute($value)
    {
        if(file_exists(storage_path('app/public/'.$value)))
        {
            return  asset('storage/'.$value);
        }
        return null;
    }

    public function getBlogs()
    {
        return $this->latest()->paginate(10);
    }

    public function scopeType($query, $type)
    {
        return  $query->where('type', $type);

    }

    public function createBlog($request)
    {
        DB::transaction(function () use ($request) {
            $blog = $this->create($request->all());
            $blog->update([
                'slug' => $blog->id.'-'.Str::slug($request->title, '-'),
            ]);

            $blog->tags()->attach($request->tags);
            $this->storeImage($blog, $request);
        });
    }

    public function updateBlog($blog, $request)
    {
        $data = $request->all();

        $data += ['slug' => $blog->id.'-'.Str::slug($request->title, '-')];

        DB::transaction(function () use ($data, $blog, $request){
            $blog->update($data);
            $blog->tags()->sync($request->tags);

            if (request()->has('image'))
            {
                $this->storeImage($blog, $request);
            }
        });

        return $blog;
    }

    public function deleteBlog($blog)
    {
        $blog->delete();
    }
}

app/Http/Controllers/AdminControllers/BlogController.php
<?php

namespace App\Http\Controllers\AdminControllers;

use App\Blog;
use App\Http\Controllers\Controller;
use App\Http\Requests\BlogRequest;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class BlogController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $blog = new Blog();
        $blogs = $blog->getBlogs();
        return view('partials.admin.blog.index')->with('blogs', $blogs);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $blog = new Blog();
        $tag = new Tag();
        $tags = $tag->getTags();

        return view('partials.admin.blog.create')->with('blog', $blog)->with('tags', $tags);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BlogRequest $request)
    {
        $blog = new Blog();
        $blog->createBlog($request);

        return redirect(route('blogs.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function show(Blog $blog)
    {
        $tags = Tag::all();
        return view('partials.admin.blog.show')->with('blog', $blog)->with('tags', $tags);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function edit(Blog $blog)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function update(BlogRequest $request, Blog $blog)
    {
        $blog->updateBlog($blog, $request);
        return redirect(route('blogs.index'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Blog  $blog
     * @return \Illuminate\Http\Response
     */
    public function destroy(Blog $blog)
    {
        if (file_exists(storage_path('app/public/'.$blog->getOriginal('image'))))
        {
            unlink(storage_path('app/public/'.$blog->getOriginal('image')));
        }
        $blog->deleteBlog($blog);
        return redirect(route('blogs.index'));

    }
}

app/Http/Controllers/ClientControllers/BlogController.php
<?php

namespace App\Http\Controllers\ClientControllers;

use App\Blog;
use App\Category;
use App\Comment;
use App\Http\Controllers\Controller;
use App\Tag;

class BlogController extends Controller
{
    public function index()
    {
        $blogs = Blog::type('blog')->latest()->get();
        return view('partials.client._blog.base')
            ->with('blogs', $blogs);
    }

    public function show(Blog $blog)
    {
        return view('partials.client._blogdetail.base')
            ->with('blog', $blog);
    }


}

resources/views/partials/admin/blog/contentheader.blade.php
<div class="kt-subheader  kt-grid__item" id="kt_subheader">
    <div class="kt-container  kt-container--fluid ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">Dashboard</h3>
            <span class="kt-subheader__separator kt-subheader__separator--v"></span>
            <span class="kt-subheader__desc">Blogs</span>
            <a href="{{ route('blogs.create') }}" class="btn btn-label-warning btn-bold btn-sm btn-icon-h kt-margin-l-10"> Add new </a>
        </div>
    </div>
</div>

resources/views/partials/admin/blog/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="kt-portlet">

        <!--begin::Form-->
        <form class="kt-form" action="{{ route('blogs.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            @include('partials.admin.blog.form')
            <div class="kt-portlet__foot">
                <div class="kt-form__actions">
                    <div class="row">
                        <div class="col-10">
                            <button type="submit" class="btn btn-brand btn btn-primary">Submit</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>

        <!--end::Form-->
    </div>
@endsection

resources/views/partials/admin/blog/form.blade.php
<div class="kt-subheader  kt-grid__item" id="kt_subheader">
    <div class="kt-container  kt-container--fluid ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">Dashboard</h3>
            <span class="kt-subheader__separator kt-subheader__separator--v"></span>
            <span class="kt-subheader__desc">Blog</span>
        </div>
    </div>
</div>
<div class="kt-portlet__body">
    <div class="form-group">
        <label>Title</label>
        <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" placeholder="Enter title" maxlength="100" value="{{ old('title') ?? $blog->title }}">
        @error('title')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
    <div class="form-group">
        <label>Excerpt</label>
        <input type="text" class="form-control @error('excerpt') is-invalid @enderror" name="excerpt" placeholder="Enter excerpt" value="{{ old('excerpt') ?? $blog->excerpt }}" maxlength="100">
        @error('excerpt')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
    <div class="form-group">
        <label>body</label>
        <textarea id="body" name="body" class="@error('body') is-invalid @enderror">{{ old('body') ?? $blog->body }}</textarea>
        @error('body')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>
    <div class="form-group">
        <div><label>Tags</label></div>
        <select name="tags[]" class="form-control" multiple>
            @foreach($tags as $tag)
                <option value="{{ $tag->id }}">{{ $tag->name }}</option>
            @endforeach
        </select>
    </div>
    <div class="form-group">
        <div><label>Type</label></div>
        <select name="type" class="form-control">
            <option value="blog" {{ $blog->type == 'blog' ? 'selected' : '' }}>Blog</option>
            <option value="news" {{ $blog->type == 'news' ? 'selected' : '' }}>News</option>
            <option value="scholarships" {{ $blog->type == 'scholarships' ? 'selected' : '' }}>Scholarships</option>
            <option value="job's ads" {{ $blog->type == 'job_ads' ? 'selected' : '' }}>Job's Ads</option>
        </select>
    </div>
    <div class="form-group">
        <label>Title Image</label>
        <input type="file" class="form-control @error('image') is-invalid @enderror" name="image" value="{{ old('image') ?? $blog->image }}">
        @error('image')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>

</div>

resources/views/partials/admin/blog/index.blade.php
@extends('layouts.admin')

@section('content')

    @include('partials.admin.blog.contentheader')

    <div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
        <div class="kt-portlet kt-portlet--mobile">
            <div class="kt-portlet__body kt-portlet__body--fit">
                <!--begin: Datatable -->
                <table width="100%" class="table table-hover table-bordered">
                    <thead>
                    <tr>
                        <th title="Field #1">Blog ID</th>
                        <th title="Field #2">Blog Title</th>
                        <th title="Field #2">Type</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach($blogs as $blog)
                            <tr>
                                <td scope="row">{{ $blog->id }}</td>
                                <td>{{ $blog->title }}</td>
                                <td>{{ $blog->type }}</td>
{{--                                <td><a href="{{ route('jobsTests.show', $jobTest->id) }}">{{ $jobTest->name }}</a></td>--}}
                                <td>
                                    <form action="{{ route('blogs.destroy', ['blog' => $blog]) }}" method="post" class="inline-block">
                                        <span><a href="{{ route('blogs.show', ['blog' => $blog] ) }}" class="btn btn-label-primary btn-bold btn-sm btn-icon-h kt-margin-l-10">Edit</a></span>
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-label-danger btn-bold btn-sm btn-icon-h kt-margin-l-10">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                <div class="row" style="font-size: 12px">
                    <div class="col-12 d-flex justify-content-center pt-3">
                        {{$blogs->links()}}
                    </div>
                </div>
                <!--end: Datatable -->
            </div>
        </div>
    </div>

@endsection

resources/views/partials/admin/blog/show.blade.php
@extends('layouts.admin')

@section('content')
    <div class="kt-portlet">

        <!--begin::Form-->
        <form class="kt-form" action="{{ route('blogs.update', ['blog' => $blog]) }}" method="post" enctype="multipart/form-data">
            @csrf
            @method('PATCH')
            @include('partials.admin.blog.form')
            <div class="kt-portlet__foot">
                <div class="kt-form__actions">
                    <div class="row">
                        <div class="col-10">
                            <button type="submit" class="btn btn-label-primary btn-bold btn-sm btn-icon-h kt-margin-l-10">Update</button>
                        </div>
                    </div>
                </div>
            </div>
            @if($blog->image)
                <div class="align-center p-5">
                    <img src="{{ $blog->image }}" height="250" width="250" class="img-fullwidth" alt="">
                </div>
            @endif
        </form>
        <!--end::Form-->
    </div>
@endsection