routes/admin.php
<?php

Route::get('/dashboard', 'DashboardController@index')->name('admin.index');



Route::resource('subjects', 'SubjectController');

Route::get('files/create', 'FileUploadController@create')->name('files.create');
Route::post('files', 'FileUploadController@store')->name('files.store');
Route::get('files/{subject}/{file}', 'FileUploadController@show')->name('files.show');
Route::get('files', 'FileUploadController@index')->name('files.index');
Route::patch('files/{file}', 'FileUploadController@update')->name('files.update');
Route::delete('files/{file}', 'FileUploadController@destroy')->name('files.destroy');
//Route::resource('fileable.files', 'FileUploadController')->except(['fileable.file.index', 'fileable.file.create', 'fileable.file.store']);

Route::get('downloadables/create', 'DownloadableController@create')->name('downloadables.create');
Route::post('downloadables', 'DownloadableController@store')->name('downloadables.store');
Route::get('downloadables/{category}/{downloadable}', 'DownloadableController@show')->name('downloadables.show');
Route::get('downloadables', 'DownloadableController@index')->name('downloadables.index');
Route::patch('downloadables/{downloadable}', 'DownloadableController@update')->name('downloadables.update');
Route::delete('downloadables/{downloadable}', 'DownloadableController@destroy')->name('downloadables.destroy');
//Route::resource('downloadables', 'DownloadableController');

Route::post('jobs', 'JobController@store')->name('jobs.store');
Route::get('jobs', 'JobController@index')->name('jobs.index');
Route::get('jobs/{subCategory}/{job}', 'JobController@show')->name('jobs.show');
Route::patch('jobs/{job}', 'JobController@update')->name('jobs.update');
Route::delete('jobs/{job}', 'JobController@destroy')->name('jobs.destroy');
Route::get('jobs/create','JobController@create')->name('jobs.create');
//Route::resource('jobs', 'JobController');

//Route::resource('tests', 'TestController');
//Route::resource('jobs-tests', 'JobController');

Route::resource('tags', 'TagController');

Route::resource('blogs', 'BlogController');

Route::resource('useruploads', 'UserUploadController');

Route::get('useruploads/{userupload}', 'DownloadController@download')->name('downloads.download');

Route::get('user', 'DownloadController@sample')->name('downloads.sample');

Route::get('user-downloadables', 'DownloadableController@index')->name('user-downloadables.index');


Route::get('subject-quizzes/create', 'SubjectQuizController@create')->name('subject-quizzes.create');
Route::post('subject-quizzes', 'SubjectQuizController@store')->name('subject-quizzes.store');
Route::get('subject-quizzes/{subject}/{subject_quiz}', 'SubjectQuizController@show')->name('subject-quizzes.show');
Route::get('subject-quizzes', 'SubjectQuizController@index')->name('subject-quizzes.index');
Route::patch('subject-quizzes/{subject_quiz}', 'SubjectQuizController@update')->name('subject-quizzes.update');
Route::delete('subject-quizzes/{subject_quiz}', 'SubjectQuizController@destroy')->name('subject-quizzes.destroy');
//Route::resource('subject-quizzes', 'SubjectQuizController');

Route::get('job-quizzes/create', 'JobQuizController@create')->name('job-quizzes.create');
Route::post('job-quizzes', 'JobQuizController@store')->name('job-quizzes.store');
Route::get('job-quizzes/{job}/{job_quiz}', 'JobQuizController@show')->name('job-quizzes.show');
Route::get('job-quizzes', 'JobQuizController@index')->name('job-quizzes.index');
Route::patch('job-quizzes/{job_quiz}', 'JobQuizController@update')->name('job-quizzes.update');
Route::delete('job-quizzes/{job_quiz}', 'JobQuizController@destroy')->name('job-quizzes.destroy');
//Route::resource('job-quizzes', 'JobQuizController');

Route::get('test-quizzes/create', 'TestQuizController@create')->name('test-quizzes.create');
Route::post('test-quizzes', 'TestQuizController@store')->name('test-quizzes.store');
Route::get('test-quizzes/{category}/{test_quiz}', 'TestQuizController@show')->name('test-quizzes.show');
Route::get('test-quizzes', 'TestQuizController@index')->name('test-quizzes.index');
Route::patch('test-quizzes/{test_quiz}', 'TestQuizController@update')->name('test-quizzes.update');
Route::delete('test-quizzes/{test_quiz}', 'TestQuizController@destroy')->name('test-quizzes.destroy');
//Route::resource('test-quizzes', 'TestQuizController');

//Route::resource('course-quizzes', 'CourseQuizController');

//Route::post('course/{quiz}/{file_id}', 'CourseQuizController@deleteFile')->name('course.destroyFile');
Route::get('job-quizz/{job_quiz}/{file_id}', 'JobQuizController@deleteFile')->name('job-quiz.destroyFile');
Route::get('test-quizz/{test_quiz}/{file_id}', 'TestQuizController@deleteFile')->name('test-quiz.destroyFile');
Route::get('quiz/{quiz}/{file_id}', 'SubjectQuizController@deleteFile')->name('quiz.destroyFile');


Route::get('slider', 'SliderController@index')->name('slider');
//
Route::post('slider/{slider}/update', 'SliderController@update')->name('slider.update');

Route::get('about', 'AboutController@index')->name('admin.about');
//
Route::post('about/{about}/update', 'AboutController@update')->name('about.update');

Route::get('contact', 'ContactController@index')->name('admin.contact');
//
Route::post('contact/{contact}/update', 'ContactController@update')->name('contact.update');

Route::get('banner', 'BannerController@index')->name('banner');
//
Route::post('banner/{banner}/update', 'BannerController@update')->name('banner.update');

//Route::resource('slider', 'SliderController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('layouts.client');
//});

//Auth::routes();
Route::post('login/user', 'Auth\LoginController@login')->name('login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
Route::get('password/confirm', 'Auth\ConfirmPasswordController@showConfirmForm')->name('password.confirm');
Route::post('password/confirm', 'Auth\ConfirmPasswordController@confirm');

Route::get('/', 'ClientControllers\HomeController@index')->name('home');
//Route::get('/', function (){
//    return view('home',[
//        'subjects' => \App\Subject::all(),
//    ]);
//});
//Route::get('/about', 'ClientControllers\AboutController@index')->name('about');
//Route::get('/contact', 'ClientControllers\ContactController@index')->name('contact');
//Route::get('/jobs', 'ClientControllers\JobController@index')->name('jobs');
//Route::get('/tests', 'ClientControllers\AdmissionTestController@index')->name('tests');
//Route::get('/blogs', 'ClientControllers\BlogController@index')->name('blogs');
//Route::get('/blogs/detail', 'ClientControllers\BlogController@show')->name('blogs/detail');

resources/views/partials/client/_header/base.blade.php
<header id="header" class="header">

    @include('partials.client._header.topbar')
    @include('partials.client._header.brand')
    @include('partials.client._header.navbar')
</header>

resources/views/partials/client/_header/brand.blade.php
<div class="header-middle p-0 bg-lightest xs-text-center customStyleHeader">
    <div class="container customContainer">
        <div class="row">
            <div class="col-md-2 customsetColMd3Logo">
                <div class="widget no-border m-0">
                    <a class="menuzord-brand pull-left flip xs-pull-center mb-15" href="{{ route('home') }}"><img src="{{ asset('assets/images/logo.png') }}" alt=""></a>
                </div>
            </div>
            <div class="col-md-10 pull-right" id="loginForm">
                <div class="widget no-border sm-text-center mt-10 mb-10 m-0 customClasswidget">
                    @guest
                        <form method="POST" class="customForm" action="{{ route('login') }}">
                            @method('POST')
                            @csrf
                            <div class="form-group row customRowFormGroup">
{{--                                <label for="email" class="col-lg-6">{{ __('E-Mail Address') }}</label>--}}

                                <div class="col-md-12">
                                    <input id="email" placeholder="Email/Phone" class="form-control-sm customClass @error('_email') is-invalid @enderror" maxlength="100" name="_email" value="{{ old('_email') }}" required autofocus>
{{--                                    @error('_email')--}}
{{--                                    <span class="font-9 text-danger" role="alert">--}}
{{--                                        <strong>{{ $errors->first('_email') }}</strong>--}}
{{--                                    </span>--}}
{{--                                    @enderror--}}
                                </div>
                            </div>

                            <div class="form-group row customRowFormGroup">
{{--                                <label for="password" class="col-lg-6">{{ __('Password') }}</label>--}}

                                <div class="col-md-12">
                                    <input id="password" type="password" placeholder="Password" class="form-control-sm customClass @error('_password') is-invalid @enderror" maxlength="100" name="_password" value="{{ old('_password') }}" required autocomplete="current-password">

                                    @if (Route::has('password.request'))
                                        <br/>
                                        <span>
                                            <a class="customPasswordReset" href="{{ route('password.request') }}" style="position: inherit; float: left">
                                                {{ __('Forgot Your Password?') }}
                                            </a>
                                        </span>
                                    @endif
{{--                                    @error('_password')--}}
{{--                                    <span class="invalid-feedback" role="alert">--}}
{{--                                        <strong>{{ $message }}</strong>--}}
{{--                                    </span>--}}
{{--                                    @enderror--}}
                                </div>
                            </div>

                            <div class="form-group row customRowCheckBox">
                                <div class="col-lg-6">
                                    <div class="form-check customRemember" style="display: none;">

                                        <span class="customTextCheck"><input class="form-check-input" type="checkbox" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}></span>
                                        <span class="customTextTRemember"><label class="form-check-label" for="remember">
                                            {{ __('Remember Me') }}
                                        </label></span>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4 customLoginSection" style="bottom: 15px">
                                    <button type="submit" class="btn btn-primary customLoginStyle" style="background: #F2184E !important;border: 0px !important;">
                                        {{ __('Login') }}
                                    </button>
                                    @if (Route::has('register'))
                                        <a class="btn btn-primary customRegisterStyle" style="background: #F2184E !important;border: 0px !important;" href="{{ route('register') }}">{{ __('Register') }}</a>
                                    @endif
{{--                                    <button type="submit" class="btn btn-primary customRegisterStyle" style="background: #F2184E !important;border: 0px !important;">--}}
{{--                                        {{ __('Register') }}--}}
{{--                                    </button>--}}
                                </div>
                            </div>
                        </form>
                    @else
                        @php
                            $userId = (\Auth::user()->id);
                            $totalQuestions = \App\ConciseRecord::where('user_id', '=', $userId)->sum('total_questions');
                            $correctAnswers = \App\ConciseRecord::where('user_id', '=', $userId)->sum('correct_answers');
                            $avgCorrectAnswers = \App\ConciseRecord::where('user_id', '=', $userId)->avg('correct_answers');
                        @endphp
                        <div class="customContainer mb-1">
                            @if(Auth::user()->getOriginal('image'))
                                @if(file_exists(storage_path('app/public/'.Auth::user()->getOriginal('image'))))
                                    <div class="inline-block align-top">
                                        <a href="{{ route('profile.show', ['profile' => Auth::user() ]) }}"><img src="{{ Auth::user()->image }}" class="border-radius-10px" height="60" width="60" alt="">
                                        </a>
                                    </div>
                                @endif
                            @endif
                            <div class="inline-block align-left">
                                <h6>questions attempted: <span class="setColor">{{ \App\ConciseRecord::where('user_id', Auth::id())->sum('total_questions') }}</span></h6>
                                <h6>correct answers: <span class="setColor">{{ \App\ConciseRecord::where('user_id', Auth::id())->sum('correct_answers') }}</span></h6>
                                <h6>wrong answers: <span class="setColor">{{ \App\ConciseRecord::where('user_id', Auth::id())->sum('total_questions') - \App\ConciseRecord::where('user_id', Auth::id())->sum('correct_answers') }}</span></h6>
                            </div>
                        </div>
{{--                        <div class="customContnaainer flex flex-row border-1px">--}}
{{--                        </div>--}}
{{--                        <div class="container customContainer ">--}}
{{--                            --}}
{{--                        </div>--}}
                    @endguest

                </div>
            </div>

        </div>
    </div>
</div>

resources/views/partials/client/_header/navbar.blade.php
<div class="header-nav">
    <div class="header-nav-wrapper navbar-scrolltofixed bg-theme-colored border-bottom-theme-color-2-1px">
        <div class="container customNavContainer">
            <nav id="menuzord" class="menuzord bg-theme-colored pull-left flip menuzord-responsive">
                <ul class="menuzord-menu">
                    @foreach($categories as $category)
                            @if($category->subCategories->count() > 0)
                            <li><a href="#">{{ $category->name }}</a>
                                <ul class="dropdown">
                                    @foreach($category->subCategories as $subCategory)
                                        @if($category->id == 1)
                                        <li><a href="{{ route('jobs.jobs', ['subCategory' => $subCategory]) }}">{{ $subCategory->name }}</a></li>
                                        @else
                                            <li><a href="{{ route('test.quizzes.show', ['subCategory' => $subCategory]) }}">{{ $subCategory->name }}</a>
                                        @endif
                                    @endforeach
                                </ul>
                            </li>
{{--                            @else--}}
{{--                                <li><a href="{{ route('test.quizzes.show', ['category' => $category]) }}">{{ $category->name }}</a>--}}
                            @endif
                    @endforeach

                    @if($subjects->count() > 0)
                        <li><a href="#">Subjects</a>
                            <ul class="dropdown" style="max-height: 200px; overflow: scroll; overflow-x: hidden">
                                @foreach($subjects as $subject)
                                    <li><a href="{{ route('subject.quizzes.show', ['subject' => $subject]) }}">{{ $subject->name }}</a></li>
                                @endforeach
                            </ul>
                        </li>
                    @endif

                    <li><a href="{{ route('client.blogs') }}">Blogs</a>

                    <li><a href="{{ route('client.news') }}">News</a>

                    <li>
                        <a href="{{ route('client.scholarships') }}">Scholarships</a>
                    </li>
{{--                    <li>--}}
{{--                        <a href="{{ route('client.past-papers') }}">Past Papers</a>--}}
{{--                    </li>--}}
                    <li>
                        <a href="{{ route('client.job-ads') }}">Find Jobs</a>
                    </li>

                    @if($downloadables->count() > 0)
                        <li><a href="#">Downloads</a>
                            <ul class="dropdown">
                                @foreach($downloadables as $downloadable)
                                    <li>
                                        <a href="{{ route('client.downloadables.show', ['downloadable' => $downloadable]) }}">{{ $downloadable->category }}</a>
                                    </li>
                                @endforeach
                            </ul>
                        </li>
                    @endif

                </ul>
            </nav>
        </div>
    </div>
</div>

resources/views/partials/client/_header/topbar.blade.php
<div class="header-top bg-theme-color-2 sm-text-center p-0">
    @if($errors->first('_email') || $errors->first('_password'))
        <div class="alert alert-danger" id="success-alert">
            <strong class="text-white mr-2">Incorrect </strong>credentials.
        </div>
    @endif
    <div class="container customHeaderContainer">
        <div class="row">
            <div class="col-md-12">
                <div class="widget no-border m-0" id="hideResponsive">
                    <ul class="list-inline font-15 sm-text-center mt-10">
                        <li>
                            <a class="text-white" href="{{ route('home') }}">Home</a>
                        </li>
                        <li class="text-white">|</li>
                        <li>
                            <a class="text-white" href="{{ route('about') }}">About us</a>
                        </li>
                        <li class="text-white">|</li>
                        <li>
                            <a class="text-white" href="{{ route('contact') }}">Contact us</a>
                        </li>
                        <li class="text-white">|</li>
                        <li>
                            <a class="text-white" href="{{ route('useruploads.create') }}" target="_blank">Add Data</a>
                        </li>
                        <li>
                            <a href="https://www.youtube.com/channel/UCw_9uqq4lCsbCPC6hKJ9mDg/?guided_help_flow=5"><i class="fab font-22 text-white fa-youtube" style="font-size: 40px !important;padding: 0px;margin: -26px;position: absolute;margin-left: -2px;"></i></a>
                        </li>
                        <li class="flex flex-column" style="margin-left: 12%">
                            <span class="welcome">Welcome to Learn Relief</span>
                        </li>


                    @if(\Auth::user())
                        <li class="nav-item dropdown customDropDownUser" onmouseover="openDropDown()" onmouseleave="closeDropDown()">
                            <img alt="" class="inline-block flex-row customImage" height="50" src="{{ Auth::user()->image }}" onerror="this.src='/images/noimage.png'">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"  aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
{{--                                <span class="caret"></span>--}}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" >
                                @if(Auth::user()->is_admin)
                                    <a class="dropdown-item" href="{{ route('admin.index') }}">
                                        Admin
                                    </a>
                                @endif
                                <a class="dropdown-item" href="{{ route('profile.show', ['profile' => Auth::user() ]) }}">
                                    Edit profile
                                </a>
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                     @endif
                    </ul>
                </div>
                <div class="widget no-border m-0" id="showResposnive" style="display: none">
                    <img src="{{asset('images/humburgerIcon.png')}}" class="imageBurger" />
                </div>
                <div class="widget no-border m-0">
                    <ul class="openUlBox">
                        <li>
                            <a class="text-white" href="{{ route('home') }}">Home</a>
                        </li>
                        <li>
                            <a class="text-white" href="{{ route('about') }}">About us</a>
                        </li>
                        <li>
                            <a class="text-white" href="{{ route('contact') }}">Contact us</a>
                        </li>
                        <li>
                            <a class="text-white" href="{{ route('useruploads.create') }}">Add Data</a>
                        </li>
                        <li> <a href="https://www.youtube.com/channel/UCw_9uqq4lCsbCPC6hKJ9mDg/?guided_help_flow=5" target="_blank"><i class="fab text-white fa-youtube"style="color: red"></i></a></li>

                        @if(\Auth::user())
                            <li class="nav-item dropdown customDropDownUser2" onmouseover="openDropDown()" onmouseleave="closeDropDown()">
                                <img alt="" class="inline-block flex-row customImage" height="50" src="{{ Auth::user()->image }}" onerror="this.src='/images/noimage.png'">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                </a>
                                <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
                                    @if(Auth::user()->is_admin)
                                        <a class="dropdown-item" href="{{ route('admin.index') }}">
                                            Admin
                                        </a>
                                    @endif
                                    <a class="dropdown-item" href="{{ route('profile.show', ['profile' => Auth::user() ]) }}">
                                        Edit profile
                                    </a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>