routes/admin.php
<?php

Route::get('/dashboard', 'DashboardController@index')->name('admin.index');



Route::resource('subjects', 'SubjectController');

Route::get('files/create', 'FileUploadController@create')->name('files.create');
Route::post('files', 'FileUploadController@store')->name('files.store');
Route::get('files/{subject}/{file}', 'FileUploadController@show')->name('files.show');
Route::get('files', 'FileUploadController@index')->name('files.index');
Route::patch('files/{file}', 'FileUploadController@update')->name('files.update');
Route::delete('files/{file}', 'FileUploadController@destroy')->name('files.destroy');
//Route::resource('fileable.files', 'FileUploadController')->except(['fileable.file.index', 'fileable.file.create', 'fileable.file.store']);

Route::get('downloadables/create', 'DownloadableController@create')->name('downloadables.create');
Route::post('downloadables', 'DownloadableController@store')->name('downloadables.store');
Route::get('downloadables/{category}/{downloadable}', 'DownloadableController@show')->name('downloadables.show');
Route::get('downloadables', 'DownloadableController@index')->name('downloadables.index');
Route::patch('downloadables/{downloadable}', 'DownloadableController@update')->name('downloadables.update');
Route::delete('downloadables/{downloadable}', 'DownloadableController@destroy')->name('downloadables.destroy');
//Route::resource('downloadables', 'DownloadableController');

Route::post('jobs', 'JobController@store')->name('jobs.store');
Route::get('jobs', 'JobController@index')->name('jobs.index');
Route::get('jobs/{subCategory}/{job}', 'JobController@show')->name('jobs.show');
Route::patch('jobs/{job}', 'JobController@update')->name('jobs.update');
Route::delete('jobs/{job}', 'JobController@destroy')->name('jobs.destroy');
Route::get('jobs/create','JobController@create')->name('jobs.create');
//Route::resource('jobs', 'JobController');

//Route::resource('tests', 'TestController');
//Route::resource('jobs-tests', 'JobController');

Route::resource('tags', 'TagController');

Route::resource('blogs', 'BlogController');

Route::resource('useruploads', 'UserUploadController');

Route::get('useruploads/{userupload}', 'DownloadController@download')->name('downloads.download');

Route::get('user', 'DownloadController@sample')->name('downloads.sample');

Route::get('user-downloadables', 'DownloadableController@index')->name('user-downloadables.index');


Route::get('subject-quizzes/create', 'SubjectQuizController@create')->name('subject-quizzes.create');
Route::post('subject-quizzes', 'SubjectQuizController@store')->name('subject-quizzes.store');
Route::get('subject-quizzes/{subject}/{subject_quiz}', 'SubjectQuizController@show')->name('subject-quizzes.show');
Route::get('subject-quizzes', 'SubjectQuizController@index')->name('subject-quizzes.index');
Route::patch('subject-quizzes/{subject_quiz}', 'SubjectQuizController@update')->name('subject-quizzes.update');
Route::delete('subject-quizzes/{subject_quiz}', 'SubjectQuizController@destroy')->name('subject-quizzes.destroy');
//Route::resource('subject-quizzes', 'SubjectQuizController');

Route::get('job-quizzes/create', 'JobQuizController@create')->name('job-quizzes.create');
Route::post('job-quizzes', 'JobQuizController@store')->name('job-quizzes.store');
Route::get('job-quizzes/{job}/{job_quiz}', 'JobQuizController@show')->name('job-quizzes.show');
Route::get('job-quizzes', 'JobQuizController@index')->name('job-quizzes.index');
Route::patch('job-quizzes/{job_quiz}', 'JobQuizController@update')->name('job-quizzes.update');
Route::delete('job-quizzes/{job_quiz}', 'JobQuizController@destroy')->name('job-quizzes.destroy');
//Route::resource('job-quizzes', 'JobQuizController');

Route::get('test-quizzes/create', 'TestQuizController@create')->name('test-quizzes.create');
Route::post('test-quizzes', 'TestQuizController@store')->name('test-quizzes.store');
Route::get('test-quizzes/{category}/{test_quiz}', 'TestQuizController@show')->name('test-quizzes.show');
Route::get('test-quizzes', 'TestQuizController@index')->name('test-quizzes.index');
Route::patch('test-quizzes/{test_quiz}', 'TestQuizController@update')->name('test-quizzes.update');
Route::delete('test-quizzes/{test_quiz}', 'TestQuizController@destroy')->name('test-quizzes.destroy');
//Route::resource('test-quizzes', 'TestQuizController');

//Route::resource('course-quizzes', 'CourseQuizController');

//Route::post('course/{quiz}/{file_id}', 'CourseQuizController@deleteFile')->name('course.destroyFile');
Route::get('job-quizz/{job_quiz}/{file_id}', 'JobQuizController@deleteFile')->name('job-quiz.destroyFile');
Route::get('test-quizz/{test_quiz}/{file_id}', 'TestQuizController@deleteFile')->name('test-quiz.destroyFile');
Route::get('quiz/{quiz}/{file_id}', 'SubjectQuizController@deleteFile')->name('quiz.destroyFile');


Route::get('slider', 'SliderController@index')->name('slider');
//
Route::post('slider/{slider}/update', 'SliderController@update')->name('slider.update');

Route::get('about', 'AboutController@index')->name('admin.about');
//
Route::post('about/{about}/update', 'AboutController@update')->name('about.update');

Route::get('contact', 'ContactController@index')->name('admin.contact');
//
Route::post('contact/{contact}/update', 'ContactController@update')->name('contact.update');

Route::get('banner', 'BannerController@index')->name('banner');
//
Route::post('banner/{banner}/update', 'BannerController@update')->name('banner.update');

//Route::resource('slider', 'SliderController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('layouts.client');
//});

//Auth::routes();
Route::post('login/user', 'Auth\LoginController@login')->name('login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');
Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');
Route::get('password/confirm', 'Auth\ConfirmPasswordController@showConfirmForm')->name('password.confirm');
Route::post('password/confirm', 'Auth\ConfirmPasswordController@confirm');

Route::get('/', 'ClientControllers\HomeController@index')->name('home');
//Route::get('/', function (){
//    return view('home',[
//        'subjects' => \App\Subject::all(),
//    ]);
//});
//Route::get('/about', 'ClientControllers\AboutController@index')->name('about');
//Route::get('/contact', 'ClientControllers\ContactController@index')->name('contact');
//Route::get('/jobs', 'ClientControllers\JobController@index')->name('jobs');
//Route::get('/tests', 'ClientControllers\AdmissionTestController@index')->name('tests');
//Route::get('/blogs', 'ClientControllers\BlogController@index')->name('blogs');
//Route::get('/blogs/detail', 'ClientControllers\BlogController@show')->name('blogs/detail');

app/Banner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Banner extends Model
{
    public function getImageAttribute($value)
    {
        if(file_exists(storage_path('app/public/'.$value)))
        {
            return  asset('storage/'.$value);
        }
        return null;
    }
}

resources/views/partials/client/_coursedetail/base.blade.php
@extends('layouts.client')

@section('content')

    <!-- Section: Course -->
    <section>
      <div class="container">
        <div class="row">
            <!-- Course Detail -->
            @include('partials.client._coursedetail.detail')

            <!-- Left-side-bar -->
            @include('partials.client._coursedetail.leftsidebar')

        </div>
      </div>
    </section>
@endsection

resources/views/partials/client/_coursedetail/detail.blade.php
<div class="col-md-8 blog-pull-right">
    <div class="single-service">
        <img src="{{ $quiz->image }}" onerror="this.src='{{ asset('assets/images/logo.jpeg') }}'" alt="" class="w-75">
        <h3 class="line-bottom mt-20">{{ $quiz->name }}</h3>

        <h6>{{ $quiz->description }}</h6>

        <form action="{{ route('attempt.index', ['quiz' => $quiz]) }}" method="get" class="mt-40">
            @csrf
            <h5>Select Mode</h5>
                <div>
                    <input type="radio" id="mode" name="mode" value="0" checked>
                    <label for="mode">Practice mode</label>
                </div>
                <div>
                    <input type="radio" id="mode" name="mode" value="1">
                    <label for="mode">Test mode</label>
                </div>
                <input type="hidden" name="quiz_id" value="{{ $quiz->id }}">
                <button type="submit" class="btn btn-primary customLoginStyle">Start Quiz</button>
        </form>
    </div>
</div>

resources/views/partials/client/_coursedetail/leftsidebar.blade.php
<div class="col-sm-12 col-md-4">
    <div class="sidebar sidebar-left mt-sm-30 ml-40">
        <div class="widget">
            <h4 class="widget-title line-bottom">Other <span class="text-theme-color-2">Categories</span></h4>
            <div class="services-list">

                <ul class="list list-border angle-double-right">
                    @foreach($categories as $category)
                        @if($category->subCategories->count() > 0)
                            @foreach($category->subCategories as $subCategory)
                                @if($category->id == 1)
                                    <h6><li><a href="{{ route('jobs.jobs', ['subCategory' => $subCategory]) }}">{{ $subCategory->name }}</a></li></h6>
                                @else
                                    <h6><li><a href="{{ route('test.quizzes.show', ['subCategory' => $subCategory]) }}">{{ $subCategory->name }}</a></li></h6>
                                @endif
                            @endforeach
                        @else
                        @endif
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
</div>